from yacs.config import CfgNode as CN

CONF = CN()

CONF.MODEL = CN()
CONF.MODEL.NAME = 'seg_hrnet'
CONF.MODEL.PRETRAINED = ''
CONF.MODEL.ALIGN_CORNERS = True
CONF.MODEL.NUM_OUTPUTS = 1
CONF.MODEL.EXTRA = CN(new_allowed=True)

# DATASET related params
CONF.DATASET = CN()
CONF.DATASET.ROOT = ''
CONF.DATASET.DATASET = 'cityscapes'
CONF.DATASET.NUM_CLASSES = 2
CONF.DATASET.TRAIN_SET = 'list/cityscapes/train.lst'
CONF.DATASET.EXTRA_TRAIN_SET = ''
CONF.DATASET.TEST_SET = 'list/cityscapes/val.lst'

# training
CONF.TRAIN = CN()

CONF.TRAIN.FREEZE_LAYERS = ''
CONF.TRAIN.FREEZE_EPOCHS = -1
CONF.TRAIN.NONBACKBONE_KEYWORDS = []
CONF.TRAIN.NONBACKBONE_MULT = 10

CONF.TRAIN.IMAGE_SIZE = [1024, 512]  # width * height
CONF.TRAIN.BASE_SIZE = 2048
CONF.TRAIN.DOWNSAMPLERATE = 1
CONF.TRAIN.FLIP = True
CONF.TRAIN.MULTI_SCALE = True
CONF.TRAIN.SCALE_FACTOR = 16

CONF.TRAIN.RANDOM_BRIGHTNESS = False
CONF.TRAIN.RANDOM_BRIGHTNESS_SHIFT_VALUE = 10

CONF.TRAIN.LR_FACTOR = 0.1
CONF.TRAIN.LR_STEP = [90, 110]
CONF.TRAIN.LR = 0.01
CONF.TRAIN.EXTRA_LR = 0.001

CONF.TRAIN.OPTIMIZER = 'sgd'
CONF.TRAIN.MOMENTUM = 0.9
CONF.TRAIN.WD = 0.0001
CONF.TRAIN.NESTEROV = False
CONF.TRAIN.IGNORE_LABEL = -1

CONF.TRAIN.BEGIN_EPOCH = 0
CONF.TRAIN.END_EPOCH = 484
CONF.TRAIN.EXTRA_EPOCH = 0

CONF.TRAIN.RESUME = False

CONF.TRAIN.BATCH_SIZE_PER_GPU = 32
CONF.TRAIN.SHUFFLE = True
# only using some training samples
CONF.TRAIN.NUM_SAMPLES = 0

# testing
CONF.TEST = CN()

CONF.TEST.IMAGE_SIZE = [2048, 1024]  # width * height
CONF.TEST.BASE_SIZE = 2048

CONF.TEST.BATCH_SIZE_PER_GPU = 32
# only testing some samples
CONF.TEST.NUM_SAMPLES = 0

CONF.TEST.MODEL_FILE = ''
CONF.TEST.FLIP_TEST = False
CONF.TEST.MULTI_SCALE = False
CONF.TEST.SCALE_LIST = [1]

CONF.TEST.OUTPUT_INDEX = -1

# debug
CONF.DEBUG = CN()
CONF.DEBUG.DEBUG = False
CONF.DEBUG.SAVE_BATCH_IMAGES_GT = False
CONF.DEBUG.SAVE_BATCH_IMAGES_PRED = False
CONF.DEBUG.SAVE_HEATMAPS_GT = False
CONF.DEBUG.SAVE_HEATMAPS_PRED = False


def update_config(cfg, yaml_path):
    cfg.defrost()
    cfg.merge_from_file(yaml_path)
    cfg.freeze()
